#!/usr/bin/env python3
"""Generate authoritative .xz and .zst fixtures for the deb decompression
host-tests (Feature: linux-binary-compat, P29).

Uses Python's standard `lzma` (xz/LZMA2, CRC64 check -- the xz CLI default) and
the real-zstd-backed `compression.zstd` module (Python 3.14, PEP 784) to PRODUCE
compressed streams from known payloads. Emits a Rust source file of `const`
byte arrays that the host test decompresses via `crate::deb::decompress_data`
and checks against the known payload. This is authoritative: the compressors are
the standard tools, not the same crate that decodes them.
"""
import lzma
import compression.zstd as zstd

# --- Known payloads ---------------------------------------------------------
# A: tiny. B: structured/repetitive text. C: large enough (>~8 KiB) to force the
# decoder's 8 KiB scratch buffer to fill and the streaming loop to iterate.
payloads = {
    "EMPTY": b"",
    "HELLO": b"Hello\nWorld!\n",
    "TEXT": (b"The quick brown fox jumps over the lazy dog.\n" * 64),
    "LARGE": bytes((i * 31 + (i >> 3)) & 0xFF for i in range(40000)),
}


def rust_bytes(name: str, data: bytes) -> str:
    body = ", ".join(str(b) for b in data)
    return f"pub const {name}: &[u8] = &[{body}];\n"


def main() -> None:
    out = []
    out.append("// @generated by gen_fixtures.py -- DO NOT EDIT BY HAND.")
    out.append("// Feature: linux-binary-compat -- authoritative xz/zstd fixtures for P29.")
    out.append("// xz produced by Python `lzma` (LZMA2, CRC64 check); zstd produced by")
    out.append("// Python 3.14 `compression.zstd` (the real libzstd). Each payload has a")
    out.append("// matching .xz and .zst array so the test asserts decode == payload.")
    out.append("#![allow(dead_code)]")
    out.append("")
    for name, data in payloads.items():
        xz = lzma.compress(data, format=lzma.FORMAT_XZ)  # default = CRC64 check
        zst = zstd.compress(data)
        out.append(f"// --- payload {name}: {len(data)} bytes -> xz {len(xz)} B, zst {len(zst)} B")
        out.append(rust_bytes(f"PAYLOAD_{name}", data))
        out.append(rust_bytes(f"XZ_{name}", xz))
        out.append(rust_bytes(f"ZSTD_{name}", zst))
        out.append("")
    text = "\n".join(out)
    path = "host-tests/src/properties/p29_fixtures.rs"
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"wrote {path} ({len(text)} bytes)")
    for name, data in payloads.items():
        xz = lzma.compress(data, format=lzma.FORMAT_XZ)
        zst = zstd.compress(data)
        print(f"  {name}: payload={len(data)} xz={len(xz)} zst={len(zst)}")


if __name__ == "__main__":
    main()
