// Feature: linux-binary-compat, Property 29: deb::decompress_data inverts real
// xz (LZMA2) and zstd streams produced by the standard tools.
//
// Two complementary forms of evidence:
//
//   * EXAMPLE / FIXTURE tests — authoritative `.xz` (Python `lzma`, LZMA2 +
//     CRC64, the xz CLI default) and `.zst` (Python 3.14 `compression.zstd`,
//     the real libzstd) streams for several payloads are embedded in
//     `p29_fixtures` (generated by `gen_fixtures.py`). Decompressing each via
//     `deb::decompress_data` must reproduce the exact known payload. Because the
//     compressors are the standard tools (not the crates that decode them), this
//     proves real-world `data.tar.xz` / `data.tar.zst` members decode.
//
//   * PROPERTY test — for zstd we also have a pure-Rust encoder (`ruzstd`'s
//     `compress_to_vec`), so we can round-trip *arbitrary* payloads: compress a
//     random byte vector, wrap it as an `ArMember`, and assert
//     `decompress_data(.., Zstd)` returns the original. (xz4rust is decode-only,
//     so xz cannot be exercised with random runtime-generated input; its
//     coverage is the authoritative fixtures above.)

use crate::deb::{compression_of, decompress_data, ArMember, Compression};

use super::p29_fixtures as fx;

/// Wrap raw bytes as an `ArMember` with the given member name.
fn member<'a>(name: &'a str, data: &'a [u8]) -> ArMember<'a> {
    ArMember { name, data }
}

/// `compression_of` now classifies the modern suffixes as first-class formats
/// (no longer `UnsupportedCompression`).
#[test]
fn compression_of_classifies_xz_and_zstd() {
    assert_eq!(compression_of("data.tar.xz"), Ok(Compression::Xz));
    assert_eq!(compression_of("data.tar.zst"), Ok(Compression::Zstd));
    assert_eq!(compression_of("data.tar.gz"), Ok(Compression::Gzip));
    assert_eq!(compression_of("data.tar"), Ok(Compression::None));
}

/// Each embedded authoritative `.xz` fixture decompresses to its known payload.
#[test]
fn xz_fixtures_decode_to_known_payloads() {
    let cases: &[(&str, &[u8], &[u8])] = &[
        ("EMPTY", fx::XZ_EMPTY, fx::PAYLOAD_EMPTY),
        ("HELLO", fx::XZ_HELLO, fx::PAYLOAD_HELLO),
        ("TEXT", fx::XZ_TEXT, fx::PAYLOAD_TEXT),
        ("LARGE", fx::XZ_LARGE, fx::PAYLOAD_LARGE),
    ];
    for (name, xz, payload) in cases {
        let m = member("data.tar.xz", xz);
        let got = decompress_data(&m, Compression::Xz)
            .unwrap_or_else(|e| panic!("xz fixture {name} failed to decode: {e:?}"));
        assert_eq!(got, *payload, "xz fixture {name} payload mismatch");
    }
}

/// Each embedded authoritative `.zst` fixture decompresses to its known payload.
#[test]
fn zstd_fixtures_decode_to_known_payloads() {
    let cases: &[(&str, &[u8], &[u8])] = &[
        ("EMPTY", fx::ZSTD_EMPTY, fx::PAYLOAD_EMPTY),
        ("HELLO", fx::ZSTD_HELLO, fx::PAYLOAD_HELLO),
        ("TEXT", fx::ZSTD_TEXT, fx::PAYLOAD_TEXT),
        ("LARGE", fx::ZSTD_LARGE, fx::PAYLOAD_LARGE),
    ];
    for (name, zst, payload) in cases {
        let m = member("data.tar.zst", zst);
        let got = decompress_data(&m, Compression::Zstd)
            .unwrap_or_else(|e| panic!("zstd fixture {name} failed to decode: {e:?}"));
        assert_eq!(got, *payload, "zstd fixture {name} payload mismatch");
    }
}

/// Corrupt/garbage streams must fail cleanly (Err), never panic, for both codecs.
#[test]
fn garbage_streams_fail_cleanly() {
    let garbage: &[u8] = &[0xAB, 0xCD, 0xEF, 0x00, 0x11, 0x22, 0x33, 0x44];
    let mx = member("data.tar.xz", garbage);
    assert!(decompress_data(&mx, Compression::Xz).is_err());
    let mz = member("data.tar.zst", garbage);
    assert!(decompress_data(&mz, Compression::Zstd).is_err());
}

mod props {
    use super::*;
    use proptest::prelude::*;
    use ruzstd::encoding::{compress_to_vec, CompressionLevel};

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(128))]

        /// Feature: linux-binary-compat, Property 29 (zstd round-trip).
        ///
        /// For any payload, compressing it to a real zstd frame and decoding it
        /// through `deb::decompress_data(.., Zstd)` returns the original bytes.
        /// Payloads range past the decoder's 8 KiB scratch buffer to exercise the
        /// streaming loop.
        #[test]
        fn zstd_round_trip_inverts(payload in prop::collection::vec(any::<u8>(), 0..20000)) {
            let frame = compress_to_vec(payload.as_slice(), CompressionLevel::Fastest);
            let m = member("data.tar.zst", &frame);
            let got = decompress_data(&m, Compression::Zstd)
                .expect("real zstd frame must decode");
            prop_assert_eq!(got, payload);
        }
    }
}
