// Feature: TLS server authentication (issue #14), Property 48: every trust
// anchor in the COMMITTED CA bundle is a well-formed self-signed root CA
// that the kernel's own code can validate.
//
// The bundle (`src/net/ca_bundle.rs`) is generated by `tools/gen_ca_bundle.py`
// from the curl/Mozilla CA extract and committed. If generation ever rots
// (a renamed root, a truncated DER, a bad hex line, a non-CA entry slipping
// in), the TLS verifier would silently trust nothing — or worse, something
// wrong — so P48 proves each anchor against the SAME kernel code the
// verifier will use:
//
//   * `x509::parse_certificate` accepts the DER and consumes it exactly
//     (no trailing bytes);
//   * the certificate is self-signed (subject == issuer, byte-equal);
//   * basicConstraints is present with cA=TRUE;
//   * the SPKI key type is one the verifier actually supports (never
//     `Unsupported`);
//   * the self-signature verifies via `tls_verify::verify_certificate_signature`
//     over the anchor's own key — the same dispatcher that will check chain
//     links, so a bundle root the dispatcher cannot handle fails here, at
//     build/test time, not at handshake time;
//   * labels are unique and non-empty (they feed diagnostics only, but a
//     duplicate would silently hide an anchor in logs).
//
// NOTE: proptest's assert macros expand through concat!, so messages are
// built with `format!` into locals instead of inline captures.

use crate::ca_bundle::CA_BUNDLE;
use crate::tls_verify::verify_certificate_signature;
use crate::x509::{
    find_extension, parse_basic_constraints, parse_certificate, SpkiKey, OID_EXT_BASIC_CONSTRAINTS,
};
use proptest::prelude::*;

proptest! {
    /// Each anchor parses as a self-signed, cA=TRUE certificate whose
    /// self-signature verifies with the kernel dispatcher. One case per
    /// anchor (index-driven), so a failure names the offending entry.
    #[test]
    fn bundle_anchor_is_valid_self_signed_root(idx in 0..CA_BUNDLE.len()) {
        let (label, der) = CA_BUNDLE[idx];
        let tag = format!("anchor {} ({})", idx, label);
        prop_assert!(!label.is_empty(), "{}: empty label", tag);
        prop_assert!(!der.is_empty(), "{}: empty DER", tag);
        prop_assert_eq!(der[0], 0x30, "{}: DER must start with a SEQUENCE", tag);

        let parsed = parse_certificate(der);
        prop_assert!(
            parsed.is_ok(),
            "{}: parse failed: {:?}",
            tag,
            parsed.as_ref().err()
        );
        let (cert, tail) = parsed.unwrap();
        prop_assert!(tail.is_empty(), "{}: trailing bytes after certificate", tag);

        // Self-signed root: subject == issuer (byte equality — exactly what
        // the chain builder matches anchors with).
        prop_assert_eq!(
            cert.subject,
            cert.issuer,
            "{}: subject != issuer (not self-signed)",
            tag
        );

        // MUST be a CA (the chain builder relies on anchors being CAs).
        let bc = find_extension(&cert, OID_EXT_BASIC_CONSTRAINTS);
        prop_assert!(
            bc.is_ok(),
            "{}: basicConstraints walk failed: {:?}",
            tag,
            bc.err()
        );
        let bc_opt = bc.unwrap();
        prop_assert!(
            bc_opt.is_some(),
            "{}: basicConstraints missing (not a CA)",
            tag
        );
        let is_ca = parse_basic_constraints(bc_opt.unwrap());
        prop_assert!(
            is_ca.is_ok(),
            "{}: basicConstraints parse failed: {:?}",
            tag,
            is_ca.err()
        );
        prop_assert!(
            is_ca.unwrap(),
            "{}: basicConstraints cA is not TRUE",
            tag
        );

        // The key must be on the supported surface: an Unsupported anchor
        // could never verify anything and would silently break chains.
        prop_assert!(
            !matches!(cert.spki.key, SpkiKey::Unsupported),
            "{}: unsupported SPKI algorithm",
            tag
        );

        // The self-signature must verify through the KERNEL dispatcher.
        prop_assert_eq!(
            verify_certificate_signature(cert.sig_alg, cert.tbs, cert.signature, &cert.spki.key),
            Ok(()),
            "{}: self-signature does not verify",
            tag
        );
    }

    /// Bundle-level invariants: enough anchors to be useful, unique labels
    /// (diagnostics must never hide one anchor behind another), and the one
    /// anchor the Debian mirror surface demonstrably needs.
    #[test]
    fn bundle_shape_is_sane(seed in any::<u64>()) {
        let _ = seed; // the bundle is static; the strategy keeps the property form
        prop_assert!(CA_BUNDLE.len() >= 2, "bundle suspiciously small");
        let mut labels: Vec<&str> = CA_BUNDLE.iter().map(|(l, _)| *l).collect();
        labels.sort_unstable();
        let dupes: Vec<&&str> = labels
            .windows(2)
            .filter_map(|w| if w[0] == w[1] { Some(&w[0]) } else { None })
            .collect();
        prop_assert!(dupes.is_empty(), "duplicate anchor labels: {:?}", labels);
        // ISRG Root X1 must be present: it anchors the Let's Encrypt chains
        // that deb.debian.org (the apt mirror surface) actually serves.
        prop_assert!(
            CA_BUNDLE.iter().any(|(l, _)| *l == "ISRG Root X1"),
            "bundle must contain ISRG Root X1"
        );
    }
}
