// Feature: OpenPGP repository-metadata verification (issue #32), Property 53:
// the COMMITTED Debian keyring is exactly what it claims to be, and the real
// GnuPG signatures inside it verify through this implementation.
//
// This is the analogue of P48 for the TLS trust anchors, and it is also the
// strongest interoperability test in the OpenPGP series: the committed blocks
// (`src/pkg/openpgp_keys.rs`, generated by `tools/gen_debian_keyring.py` from
// the pinned `debian-archive-keyring` package) carry signatures produced by
// Debian's own key setup —
//   * RSA-4096 PKCS#1 v1.5 with SHA-512 over the primary key and its user ID
//     (the 12/bookworm and 13/trixie archive keys), and
//   * an Ed25519 signature with SHA-256 over the primary key and user ID, made
//     with the LEGACY GnuPG Ed25519 OID (the 13/trixie stable release key),
//   * plus a subkey binding signature per archive key.
// A wrong v4 digest trailer, a missing MPI left-pad, a rejected legacy OID or a
// wrong binding composition all make this property fail — at build time, not at
// `apt update` time against a live mirror.
//
// It also pins the *shape* of the trust store: exactly the three keys the
// contract selects, no duplicates, no test key, and no key without an expiry.

use crate::openpgp::{check_pinned_key, OpenPgpError, CLOCK_FLOOR};
use super::openpgp_fixtures::{FPR_ED, FPR_EXPIRED, FPR_FOREIGN, FPR_RSA};
use crate::openpgp_keys::DEBIAN_KEYRING;
use crate::openpgp_packet as packet;

/// 2026-01-01: after the clock floor and inside every pinned validity window.
const NOW: i64 = 1_767_225_600;
/// 2036-07-13: past every pinned key's expiry.
const AFTER_EVERY_EXPIRY: i64 = 2_100_000_000;

/// The exact fingerprint set the trust store may contain. Adding a key — for
/// example the `security.debian.org` key the contract marks opt-in — is a
/// deliberate act that must update this list in the same commit.
const EXPECTED: [[u8; 20]; 3] = [
    [
        0x41, 0x58, 0x7F, 0x7D, 0xB8, 0xC7, 0x74, 0xBC, 0xCF, 0x13, 0x14, 0x16, 0x76, 0x2F, 0x67,
        0xA0, 0xB2, 0xC3, 0x9D, 0xE4,
    ],
    [
        0x04, 0xB5, 0x4C, 0x3C, 0xDC, 0xA7, 0x97, 0x51, 0xB1, 0x6B, 0xC6, 0xB5, 0x22, 0x56, 0x29,
        0xDF, 0x75, 0xB1, 0x88, 0xBD,
    ],
    [
        0xB8, 0xB8, 0x0B, 0x5B, 0x62, 0x3E, 0xAB, 0x6A, 0xD8, 0x77, 0x5C, 0x45, 0xB7, 0xC5, 0xD7,
        0xD6, 0x35, 0x09, 0x47, 0xF8,
    ],
];

#[test]
fn trust_store_shape_is_exactly_the_reviewed_set() {
    assert_eq!(DEBIAN_KEYRING.len(), EXPECTED.len(), "pinned key count");
    for want in EXPECTED {
        assert!(
            DEBIAN_KEYRING.iter().any(|k| k.fingerprint == want),
            "pinned key {} is missing from the trust store",
            hex(&want)
        );
    }
    for (i, key) in DEBIAN_KEYRING.iter().enumerate() {
        assert!(!key.label.is_empty(), "key {i} has a label");
        for other in DEBIAN_KEYRING.iter().skip(i + 1) {
            assert_ne!(key.fingerprint, other.fingerprint, "duplicate pinned fingerprint");
            assert_ne!(key.label, other.label, "duplicate pinned label");
        }
        assert!(
            key.expires.is_some(),
            "every pinned Debian key carries an expiry ({})",
            key.label
        );
        // No test key may ever leak into the production trust store.
        for test_fpr in [FPR_ED, FPR_RSA, FPR_EXPIRED, FPR_FOREIGN] {
            assert_ne!(key.fingerprint, test_fpr, "a fixture key is pinned!");
        }
    }
}

#[test]
fn pinned_metadata_agrees_with_the_committed_bytes() {
    for key in DEBIAN_KEYRING {
        let block = packet::parse_key_block(key.block)
            .unwrap_or_else(|e| panic!("{}: block parses ({e:?})", key.label));
        assert_eq!(block.primary.fingerprint(), key.fingerprint, "{}: primary fingerprint", key.label);
        assert_eq!(block.primary.algo, key.algo, "{}: algorithm", key.label);
        assert_eq!(block.primary.bits(), key.bits, "{}: key size", key.label);
        assert_eq!(block.primary.created, key.created, "{}: creation time", key.label);
        assert!(
            block.uids.iter().any(|uid| *uid == key.label.as_bytes()),
            "{}: the label is one of the key's user IDs",
            key.label
        );
        // The pinned subkey list is the block's signing subkeys, exactly.
        let mut parsed: Vec<[u8; 20]> = block.subkeys.iter().map(|s| s.key.fingerprint()).collect();
        parsed.sort();
        let mut pinned: Vec<[u8; 20]> = key.subkeys.to_vec();
        pinned.sort();
        assert_eq!(parsed, pinned, "{}: subkey fingerprints", key.label);
        // The RSA archive keys sign through a subkey; the Ed25519 stable
        // release key signs with its primary and has none.
        if key.algo == 1 {
            assert!(!key.subkeys.is_empty(), "{}: RSA key has a signing subkey", key.label);
        }
    }
}

#[test]
fn real_gnupg_key_signatures_verify() {
    // The heart of P53: every pinned key block's self-certification (RSA-4096
    // SHA-512 or Ed25519 SHA-256, made by Debian's key setup) and every subkey
    // binding signature must verify through this implementation.
    for key in DEBIAN_KEYRING {
        check_pinned_key(key, NOW)
            .unwrap_or_else(|e| panic!("{}: pinned key does not validate ({e:?})", key.label));
    }
}

#[test]
fn expiry_and_clock_are_enforced_on_the_real_keys() {
    for key in DEBIAN_KEYRING {
        assert_eq!(
            check_pinned_key(key, AFTER_EVERY_EXPIRY).unwrap_err(),
            OpenPgpError::Expired,
            "{}: expiry must be enforced",
            key.label
        );
    }
    // The 13/trixie stable release key was created 2025-03-24, after the clock
    // floor: at the floor it is not valid yet.
    let stable_key = DEBIAN_KEYRING
        .iter()
        .find(|k| k.fingerprint == EXPECTED[0])
        .expect("stable release key is pinned");
    assert_eq!(
        check_pinned_key(stable_key, CLOCK_FLOOR).unwrap_err(),
        OpenPgpError::NotYetValid
    );
}

#[test]
fn a_flipped_byte_in_a_pinned_block_is_caught() {
    let key = &DEBIAN_KEYRING[0];
    let mut flipped: Vec<u8> = key.block.to_vec();
    // Byte 40 is inside the primary key packet (after the 3-octet packet header
    // the body is version+creation+algorithm, then the key material): the block
    // still parses, but it is a different key and its fingerprint no longer
    // matches the pin.
    flipped[40] ^= 0x01;
    let leaked: &'static [u8] = Box::leak(flipped.into_boxed_slice());
    let mut tampered = *key;
    tampered.block = leaked;
    assert_eq!(
        check_pinned_key(&tampered, NOW).unwrap_err(),
        OpenPgpError::FingerprintMismatch
    );

    // A flip inside the user ID is caught by the label cross-check instead — the
    // two checks cover different parts of the block.
    let mut flipped: Vec<u8> = key.block.to_vec();
    flipped[100] ^= 0x01;
    let leaked: &'static [u8] = Box::leak(flipped.into_boxed_slice());
    let mut tampered = *key;
    tampered.block = leaked;
    assert_eq!(
        check_pinned_key(&tampered, NOW).unwrap_err(),
        OpenPgpError::KeyMetadataMismatch
    );

    // The unmodified copy still validates (the checks are not vacuous).
    check_pinned_key(key, NOW).expect("control");
}

#[test]
fn clock_floor_matches_the_tls_verifier() {
    // One clock policy in the kernel: the OpenPGP verifier must not drift from
    // the TLS chain verifier's floor (an unset RTC refuses both).
    assert_eq!(CLOCK_FLOOR, crate::tls_chain::CLOCK_FLOOR);
}

#[test]
fn e2e_test_anchor_is_well_formed_and_not_in_the_production_store() {
    use crate::openpgp_test_keys::{TEST_KEY_PRIMARY, TEST_TRUST_ANCHORS};
    use crate::openpgp_packet as packet;

    // The selftest/HV build verifies against the three Debian keys plus the test
    // key; the production store must NOT contain the test key.
    assert_eq!(TEST_TRUST_ANCHORS.len(), DEBIAN_KEYRING.len() + 1);
    for key in DEBIAN_KEYRING {
        assert!(
            TEST_TRUST_ANCHORS
                .iter()
                .any(|k| k.fingerprint == key.fingerprint),
            "the test anchor table must keep every pinned Debian key"
        );
    }
    assert!(
        !DEBIAN_KEYRING
            .iter()
            .any(|k| k.fingerprint == TEST_KEY_PRIMARY.fingerprint),
        "the E2E test key must never be part of the production trust store"
    );

    // The test key is generated by `tools/openpgp_sign.py` (hand-written OpenPGP
    // packets), so validate it with the kernel's own verifier: fingerprint,
    // metadata, user ID and self-certification must all check out.
    let parsed = packet::parse_key_block(TEST_KEY_PRIMARY.block).expect("test block parses");
    assert_eq!(parsed.primary.fingerprint(), TEST_KEY_PRIMARY.fingerprint);
    assert_eq!(parsed.primary.algo, TEST_KEY_PRIMARY.algo);
    assert_eq!(parsed.primary.bits(), TEST_KEY_PRIMARY.bits);
    assert_eq!(parsed.primary.created, TEST_KEY_PRIMARY.created);
    assert!(parsed
        .uids
        .iter()
        .any(|uid| *uid == TEST_KEY_PRIMARY.label.as_bytes()));
    check_pinned_key(&TEST_KEY_PRIMARY, NOW).expect("test anchor validates");
}

fn hex(fpr: &[u8; 20]) -> String {
    fpr.iter().map(|b| format!("{b:02X}")).collect()
}
