"""Fixture generator for host property P44 (issue #14 TLS verifier series).

Fetches two real-world certificates and writes them as Rust source constants:
  * ISRG Root X1        -- a real ROOT: v3 + BasicConstraints CA:TRUE + RSA-4096 SPKI.
  * deb.debian.org leaf -- a real LEAF: v3 + SAN dNSName shapes + CDN-issued chain.

Output (committed, regenerated only when the fixtures must be refreshed):
  host-tests/src/properties/p44_fixture_root.rs
  host-tests/src/properties/p44_fixture_leaf.rs

Run from the repo root: python tools/fetch_p44_fixtures.py
"""
import binascii
import socket
import ssl
import urllib.request

ISRG_URL = "https://letsencrypt.org/certs/isrgrootx1.der"
OUT_ROOT = "host-tests/src/properties/p44_fixture_root.rs"
OUT_LEAF = "host-tests/src/properties/p44_fixture_leaf.rs"

HEADER = """\
// GENERATED by tools/fetch_p44_fixtures.py -- real-world X.509 DER fixture for
// property P44 (TLS verifier series, issue #14). Refresh only by re-running
// the script; structural assertions in p44.rs must keep passing.

"""


def leaf_der(host: str) -> bytes:
    ctx = ssl.create_default_context()
    with socket.create_connection((host, 443), timeout=15) as sock:
        with ctx.wrap_socket(sock, server_hostname=host) as tls:
            return tls.getpeercert(binary_form=True)


def write_rust(path: str, const_name: str, der: bytes) -> None:
    hexs = binascii.hexlify(der).decode("ascii")
    with open(path, "w", newline="\n") as f:
        f.write(HEADER)
        # One long single-quoted string; rustc handles arbitrarily long lines.
        f.write(f'pub const {const_name}: &str = "{hexs}";\n')


def main() -> None:
    root = urllib.request.urlopen(ISRG_URL, timeout=30).read()
    write_rust(OUT_ROOT, "ROOT_X1_DER_HEX", root)

    leaf = leaf_der("deb.debian.org")
    write_rust(OUT_LEAF, "DEB_LEAF_DER_HEX", leaf)

    print(f"wrote {OUT_ROOT} ({len(root)} bytes), {OUT_LEAF} ({len(leaf)} bytes)")


if __name__ == "__main__":
    main()
